name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/d2d-s4ds
          git pull origin main
          cd flask-be
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart flask-blog
          sudo systemctl restart nginx